name: 'pnpm install with cache'
description: 'Doing installs'
runs:
  using: 'composite'
  steps:
    - name: 'Setting up Node'
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .node-version
        registry-url: 'https://registry.npmjs.org'

    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

    - name: Install dependencies
      shell: bash
      run: pnpm install
