<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>Altinn.ApiClients.Dialogporten.Common</AssemblyName>
        <RootNamespace>Altinn.ApiClients.Dialogporten</RootNamespace>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <BuildInParallel>false</BuildInParallel>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Altinn.ApiClients.Maskinporten" Version="10.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
        <PackageReference Include="NSec.Cryptography" Version="25.4.0" />
        <PackageReference Include="Refit.HttpClientFactory" Version="10.2.0" />
        <PackageReference Include="Refit" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Altinn.ApiClients.Dialogporten" />
        <InternalsVisibleTo Include="Altinn.ApiClients.Dialogporten.EndUser" />
        <InternalsVisibleTo Include="Altinn.ApiClients.Dialogporten.ServiceOwner" />
        <InternalsVisibleTo Include="Digdir.Library.Dialogporten.WebApiClient.Unit.Tests" />
        <InternalsVisibleTo Include="Digdir.Library.Dialogporten.WebApiClient.EndUser.Unit.Tests" />
        <InternalsVisibleTo Include="Digdir.Library.Dialogporten.WebApiClient.ServiceOwner.Unit.Tests" />
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

</Project>
