<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="10.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="appsettings.test.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="appsettings.staging.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Include="appsettings.yt01.json" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Digdir.Library.Dialogporten.E2E.Common\Digdir.Library.Dialogporten.E2E.Common.csproj" />
    </ItemGroup>

</Project>
