name: Playwright tests
on:
  workflow_call:
  workflow_dispatch:

jobs:
  playwright-tests:
    name: 'Playwright Tests (shard ${{ matrix.shard }}/3)'
    env:
      PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:5173' # vite default port
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3]

    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/install

      - name: Install Playwright Browsers
        run: pnpm --filter frontend install:browsers

      - name: Run Playwright tests
        run: pnpm --filter frontend test:playwright --shard=${{ matrix.shard }}/3

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report-shard-${{ matrix.shard }}
          path: packages/frontend/playwright-report/
          retention-days: 7

      - name: Store artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: playwright-screenshots-shard-${{ matrix.shard }}
          path: packages/frontend/test-results
          retention-days: 3

  playwright-serial-tests:
    name: 'Playwright Heavy and Performance Tests'
    env:
      PLAYWRIGHT_TEST_BASE_URL: 'http://localhost:5173' # vite default port
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: 'Checking Out Code'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/install

      - name: Install Playwright Browsers
        run: pnpm --filter frontend install:browsers

      - name: Run Playwright heavy tests
        run: pnpm --filter frontend test:playwright:heavy

      - name: Run Playwright performance tests
        run: pnpm --filter frontend test:playwright:perf

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report-serial
          path: packages/frontend/playwright-report/
          retention-days: 7

      - name: Store artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: playwright-screenshots-serial
          path: packages/frontend/test-results
          retention-days: 3
