name: Purge E2E test data

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        type: choice
        options:
          - all
          - test
          - staging
          - yt01
        default: test
      ref:
        description: "The branch or tag ref to run the cleanup on. Using default checkout ref if not provided."
        required: false
        default: main
        type: string

jobs:
  purge-e2e-test-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        environment: >-
          ${{ fromJSON(
            github.event_name == 'workflow_dispatch' &&
            inputs.environment != 'all' &&
            format('["{0}"]', inputs.environment)
            ||
            '["test","staging"]'
          ) }}

    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: ./global.json

      - name: Run E2E cleanup
        env:
          DOTNET_ENVIRONMENT: ${{ matrix.environment }}
          TokenGeneratorUser: ${{ secrets.TOKEN_GENERATOR_USERNAME }}
          TokenGeneratorPassword: ${{ secrets.TOKEN_GENERATOR_PASSWORD }}
        run: |
          dotnet test tests/Digdir.Domain.Dialogporten.E2E.Cleanup.Tests/Digdir.Domain.Dialogporten.E2E.Cleanup.Tests.csproj \
            --configuration Release \
            -- xUnit.Explicit=only
