name: Send CI/CD Status Slack Message

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      infra_status:
        type: string
        description: "Status of the infrastructure deployment job"
        default: "skipped"
      apps_status:
        type: string
        description: "Status of the apps deployment job"
        default: "skipped"
      e2e_tests_status:
        type: string
        description: "Status of the k6 end-to-end tests job"
        default: "skipped"
      graphql_e2e_tests_status:
        type: string
        description: "Status of the GraphQL end-to-end tests job"
        default: "skipped"
      webapi_e2e_tests_status:
        type: string
        description: "Status of the WebAPI end-to-end tests job"
        default: "skipped"
      performance_tests_status:
        type: string
        description: "Status of the performance tests job"
        default: "skipped"
      publish_status:
        type: string
        description: "Status of the docker image publishing job"
        default: "skipped"
      build_and_test_status:
        type: string
        description: "Status of the build and test job"
        default: "skipped"
      release_please_status:
        type: string
        description: "Status of the release-please job"
        default: "skipped"
      notify_release_created_status:
        type: string
        description: "Status of the notify-release-created job"
        default: "skipped"
    secrets:
      SLACK_BOT_TOKEN:
        required: true
      SLACK_CHANNEL_ID:
        required: true

jobs:
  send-slack-message:
    name: Send Slack message
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Determine status emojis
        id: status-emojis
        run: |
          determine_emoji() {
            local -A emoji_map=(
              [success]=":white_check_mark:"
              [failure]=":x:"
              [cancelled]=":warning:"
              [skipped]=":ballot_box_with_check:"
            )
            echo "${emoji_map[$1]:-Invalid status: $1}"
          }

          {
            echo "INFRA_EMOJI=$(determine_emoji "$INFRA_STATUS")"
            echo "APPS_EMOJI=$(determine_emoji "$APPS_STATUS")"
            echo "E2E_TESTS_EMOJI=$(determine_emoji "$E2E_TESTS_STATUS")"
            echo "GRAPHQL_E2E_TESTS_EMOJI=$(determine_emoji "$GRAPHQL_E2E_TESTS_STATUS")"
            echo "WEBAPI_E2E_TESTS_EMOJI=$(determine_emoji "$WEBAPI_E2E_TESTS_STATUS")"
            echo "PUBLISH_EMOJI=$(determine_emoji "$PUBLISH_STATUS")"
            echo "BUILD_AND_TEST_EMOJI=$(determine_emoji "$BUILD_AND_TEST_STATUS")"
            echo "PERFORMANCE_TESTS_EMOJI=$(determine_emoji "$PERFORMANCE_TESTS_STATUS")"
            echo "RELEASE_PLEASE_EMOJI=$(determine_emoji "$RELEASE_PLEASE_STATUS")"
            echo "NOTIFY_RELEASE_CREATED_EMOJI=$(determine_emoji "$NOTIFY_RELEASE_CREATED_STATUS")"
          } >> "$GITHUB_OUTPUT"
        env:
          INFRA_STATUS: ${{ inputs.infra_status }}
          APPS_STATUS: ${{ inputs.apps_status }}
          E2E_TESTS_STATUS: ${{ inputs.e2e_tests_status }}
          GRAPHQL_E2E_TESTS_STATUS: ${{ inputs.graphql_e2e_tests_status }}
          WEBAPI_E2E_TESTS_STATUS: ${{ inputs.webapi_e2e_tests_status }}
          PUBLISH_STATUS: ${{ inputs.publish_status }}
          BUILD_AND_TEST_STATUS: ${{ inputs.build_and_test_status }}
          PERFORMANCE_TESTS_STATUS: ${{ inputs.performance_tests_status }}
          RELEASE_PLEASE_STATUS: ${{ inputs.release_please_status }}
          NOTIFY_RELEASE_CREATED_STATUS: ${{ inputs.notify_release_created_status }}

      - name: Send GitHub slack message
        id: slack
        env:
          CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          ENVIRONMENT: ${{ inputs.environment }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          # statuses
          INFRA_STATUS: "${{ steps.status-emojis.outputs.INFRA_EMOJI }}"
          APPS_STATUS: "${{ steps.status-emojis.outputs.APPS_EMOJI }}"
          E2E_TESTS_STATUS: "${{ steps.status-emojis.outputs.E2E_TESTS_EMOJI }}"
          GRAPHQL_E2E_TESTS_STATUS: "${{ steps.status-emojis.outputs.GRAPHQL_E2E_TESTS_EMOJI }}"
          WEBAPI_E2E_TESTS_STATUS: "${{ steps.status-emojis.outputs.WEBAPI_E2E_TESTS_EMOJI }}"
          PUBLISH_STATUS: "${{ steps.status-emojis.outputs.PUBLISH_EMOJI }}"
          BUILD_AND_TEST_STATUS: "${{ steps.status-emojis.outputs.BUILD_AND_TEST_EMOJI }}"
          PERFORMANCE_TESTS_STATUS: "${{ steps.status-emojis.outputs.PERFORMANCE_TESTS_EMOJI }}"
          RELEASE_PLEASE_STATUS: "${{ steps.status-emojis.outputs.RELEASE_PLEASE_EMOJI }}"
          NOTIFY_RELEASE_CREATED_STATUS: "${{ steps.status-emojis.outputs.NOTIFY_RELEASE_CREATED_EMOJI }}"
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          errors: true
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload-templated: true
          payload-file-path: "./.github/slack-templates/pipeline-failed.json"
