name: "Publish nuget package"

on:
  workflow_call:
    inputs:
      version:
        description: "Version"
        required: true
        type: string
      path:
        description: "Path to project"
        required: true
        type: string
      source:
        description: "Nuget Source"
        required: true
        type: string
      ref:
        description: "The branch or tag ref to publish. Using default checkout ref if not provided."
        required: false
        default: ${{ github.ref }}
        type: string
    secrets:
      NUGET_API_KEY:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: ./global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack with debug symbols
        run: dotnet pack --configuration Release -p:Version="${VERSION}" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --output . "${PROJECT_PATH}"
        env:
          VERSION: ${{ inputs.version }}
          PROJECT_PATH: ${{ inputs.path }}

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: '*.*nupkg'

      - name: Push to NuGet
        run: dotnet nuget push *.nupkg --source "${NUGET_SOURCE}" --api-key "${NUGET_API_KEY}"
        env:
          NUGET_SOURCE: ${{ inputs.source }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
