<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <Company>Digitaliseringsdirektoratet</Company>
        <PackageTags>digdir;altinn;dialogporten</PackageTags>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/altinn/dialogporten</RepositoryUrl>
        <PackageId>Altinn.ApiClients.Dialogporten.ServiceOwner</PackageId>
        <AssemblyName>Altinn.ApiClients.Dialogporten.ServiceOwner</AssemblyName>
        <RootNamespace>Altinn.ApiClients.Dialogporten.ServiceOwner</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591,1573</NoWarn>
        <TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
        <BuildInParallel>false</BuildInParallel>
        <ImplicitUsings>true</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="/"/>
        <None Include="../../../LICENSE" Pack="true" PackagePath="/"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Digdir.Library.Dialogporten.WebApiClient.Common\Digdir.Library.Dialogporten.WebApiClient.Common.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
        <ItemGroup>
            <BuildOutputInPackage Include="@(ReferenceCopyLocalPaths)"
                                  Condition="'%(ReferenceCopyLocalPaths.ReferenceSourceTarget)' == 'ProjectReference'" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <PackageReference Include="Altinn.ApiClients.Maskinporten" Version="10.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.11" />
        <PackageReference Include="NSec.Cryptography" Version="25.4.0"/>
        <PackageReference Include="Refit" Version="10.2.0" />
        <PackageReference Include="Refit.HttpClientFactory" Version="10.2.0" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Digdir.Library.Dialogporten.WebApiClient.ServiceOwner.Unit.Tests"/>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
    </ItemGroup>

</Project>
