server {
  listen 80;

  # Statisk OIDC-discovery. BFF henter denne ved oppstart og starter ikke uten.
  location /.well-known/openid-configuration {
    default_type application/json;
    root /usr/share/nginx/html;
    add_header Cache-Control "no-store";
  }

}
