// <auto-generated>
//     This code was generated by Refitter.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Common;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Create;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Enums;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Get;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Search;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.ServiceResource;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.SystemLabels;
using Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1.Update;

#nullable enable annotations

namespace Altinn.ApiClients.Dialogporten.ServiceOwner.Features.V1
{
    public class SearchDialogEndUserContextsQueryParams
    {
        public SearchDialogEndUserContextsQueryParams(IEnumerable<string> party)
        {
            
            Party = party;
        }
        
                /// <summary>
                /// Filter by one or more owning parties
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<string> Party { get; set; }

                /// <summary>
                /// Only return context for dialogs with contentUpdatedAt greater than or equal to the supplied date-time.
                /// </summary>
        [Query] 
        public System.DateTimeOffset? ContentUpdatedAfter { get; set; }

                /// <summary>
                /// Filter by one or more system labels
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<SystemLabel>? Label { get; set; }

                /// <summary>
                /// Supply "continuationToken" for the response to get the next page of results, if hasNextPage is true
                /// </summary>
        [Query] 
        public string? ContinuationToken { get; set; }

                /// <summary>
                /// Limit the number of results per page (1-1000, default: 100)
                /// </summary>
        [Query] 
        public int? Limit { get; set; }

    }

    public class SearchDialogsQueryParams
    {
        
                /// <summary>
                /// Filter by one or more service resources
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<string>? ServiceResource { get; set; }

                /// <summary>
                /// Filter by one or more owning parties
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<string>? Party { get; set; }

                /// <summary>
                /// Filter by end user id
                /// </summary>
        [Query] 
        public string? EndUserId { get; set; }

                /// <summary>
                /// Filter by one or more extended statuses
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<string>? ExtendedStatus { get; set; }

                /// <summary>
                /// Filter by external reference
                /// </summary>
        [Query] 
        public string? ExternalReference { get; set; }

                /// <summary>
                /// Filter by status
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<DialogStatus>? Status { get; set; }

                /// <summary>
                /// If set to 'include', the result will include both deleted and non-deleted dialogs. If set to 'exclude', the result will only include non-deleted dialogs. If set to 'only', the result will only include deleted dialogs
                /// </summary>
        [Query] 
        public DeletedFilter? Deleted { get; set; }

                /// <summary>
                /// Only return dialogs created after this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? CreatedAfter { get; set; }

                /// <summary>
                /// Only return dialogs created before this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? CreatedBefore { get; set; }

                /// <summary>
                /// Only return dialogs updated after this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? UpdatedAfter { get; set; }

                /// <summary>
                /// Only return dialogs updated before this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? UpdatedBefore { get; set; }

                /// <summary>
                /// Only return dialogs with content updated after this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? ContentUpdatedAfter { get; set; }

                /// <summary>
                /// Only return dialogs with content updated before this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? ContentUpdatedBefore { get; set; }

                /// <summary>
                /// Only return dialogs that have content that has/hasn't been seen.
                /// If null, no filtering is applied
                /// If true, returns dialogs that have been seen
                /// If false, returns dialogs that have not been seen
                /// 
                /// A dialog's content is considered seen if:
                /// - It has been visited by the GET .../dialogs/{dialogId} endpoint since the last content update, and
                /// - It does not have a system label MarkedAsUnopened.
                /// </summary>
        [Query] 
        public bool? IsContentSeen { get; set; }

                /// <summary>
                /// Only return dialogs with due date after this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? DueAfter { get; set; }

                /// <summary>
                /// Only return dialogs with due date before this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? DueBefore { get; set; }

                /// <summary>
                /// Only return dialogs with visible-from date after this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? VisibleAfter { get; set; }

                /// <summary>
                /// Only return dialogs with visible-from date before this date
                /// </summary>
        [Query] 
        public System.DateTimeOffset? VisibleBefore { get; set; }

                /// <summary>
                /// Filter by process
                /// </summary>
        [Query] 
        public string? Process { get; set; }

                /// <summary>
                /// Filter by Display state
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<SystemLabel>? SystemLabel { get; set; }

                /// <summary>
                /// Whether to exclude API-only dialogs from the results. Defaults to false.
                /// </summary>
        [Query] 
        public bool? ExcludeApiOnly { get; set; }

                /// <summary>
                /// Search string for free text search. Will attempt to fuzzily match in all free text fields in the aggregate
                /// </summary>
        [Query] 
        public string? Search { get; set; }

                /// <summary>
                /// Filter by one or more labels. Multiple labels are combined with AND, i.e., all labels must match. Supports prefix matching with '*' at the end of the label. For example, 'label*' will match 'label', 'label1', 'label2', etc.
                /// </summary>
        [Query(CollectionFormat.Multi)] 
        public IEnumerable<string>? ServiceOwnerLabels { get; set; }

                /// <summary>
                /// Limit free text search to texts with this language code, e.g. 'nb', 'en'. Culture codes will be normalized to neutral language codes (ISO 639). Default: search all culture codes
                /// </summary>
        [Query] 
        public string? SearchLanguageCode { get; set; }

        [Query] 
        public string? OrderBy { get; set; }

                /// <summary>
                /// Supply "continuationToken" for the response to get the next page of results, if hasNextPage is true
                /// </summary>
        [Query] 
        public string? ContinuationToken { get; set; }

                /// <summary>
                /// Limit the number of results per page (1-1000, default: 100)
                /// </summary>
        [Query] 
        public int? Limit { get; set; }

    }

    public class CheckNotificationConditionQueryParams
    {
        public CheckNotificationConditionQueryParams(NotificationConditionType conditionType, DialogActivityType activityType)
        {
            
            ConditionType = conditionType;
            ActivityType = activityType;
        }
        
        [Query] 
        public NotificationConditionType ConditionType { get; set; }

        [Query] 
        public DialogActivityType ActivityType { get; set; }

        [Query] 
        public System.Guid? TransmissionId { get; set; }

    }

    /// <summary>Retrieve service owner labels for a dialog.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IServiceownerApi
    {
        /// <summary>Retrieve service owner labels for a dialog.</summary>
        /// <remarks>Fetches all labels associated with the service owner context of a specific dialog.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully retrieved the service owner labels.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/context/labels")]
        Task<IApiResponse<ICollection<ServiceOwnerLabel>>> GetServiceOwnerLabels(System.Guid dialogId, CancellationToken cancellationToken = default);

        /// <summary>Add a service owner label to a dialog</summary>
        /// <remarks>
        /// Add a label to the service owner context.
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="dto">dto parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog DialogServiceOwnerLabel was updated successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain", "Content-Type: application/json")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/context/labels")]
        Task<IApiResponse> CreateServiceOwnerLabel(System.Guid dialogId, [Body] CreateServiceOwnerLabel dto, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Delete a service owner label for a dialog</summary>
        /// <remarks>Removes a specific label from the service owner context of a dialog. If the label does not exist, a NotFound response is returned.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="label">label parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Successfully deleted the service owner label.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog or service owner label was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>A server side error occurred.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain")]
        [Delete("/api/v1/serviceowner/dialogs/{dialogId}/context/labels/{label}")]
        Task<IApiResponse> DeleteServiceOwnerLabel(System.Guid dialogId, string label, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Sets the system labels of a dialog</summary>
        /// <remarks>
        /// Sets the system labels of the dialog.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply EnduserContextRevision to ensure that the context is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="enduserId">enduserId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="setDialogSystemLabelRequest">setDialogSystemLabelRequest parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog system label was updated successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to update the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain", "Content-Type: application/json")]
        [Put("/api/v1/serviceowner/dialogs/{dialogId}/endusercontext/systemlabels")]
        Task<IApiResponse> SetDialogSystemLabels(System.Guid dialogId, [Body, AliasAs("SetDialogSystemLabelRequest")] SetDialogSystemLabelRequest setDialogSystemLabelRequest, [Query] string? enduserId = default, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Sets system labels for multiple dialogs</summary>
        /// <remarks>Sets the system labels for a list of dialogs, optionally including a end user context revision for each dialog.</remarks>
        /// <param name="enduserId">enduserId parameter</param>
        /// <param name="dto">dto parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog system labels was updated successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to update the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain", "Content-Type: application/json")]
        [Post("/api/v1/serviceowner/dialogs/endusercontext/systemlabels/actions/bulkset")]
        Task<IApiResponse> BulkSetDialogSystemLabels([Body] BulkSetSystemLabel dto, [Query] string? enduserId = default, CancellationToken cancellationToken = default);

        /// <summary>Gets a list of dialog transmissions</summary>
        /// <remarks>Gets the list of transmissions belonging to a dialog</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog transmission list.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to get the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/transmissions")]
        Task<IApiResponse<ICollection<DialogTransmissionSearchItem>>> SearchDialogTransmissions(System.Guid dialogId, CancellationToken cancellationToken = default);

        /// <summary>Adds a transmission to a dialog</summary>
        /// <remarks>
        /// The transmission is created with the given configuration.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="createTransmissionRequest">createTransmissionRequest parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>201</term>
        /// <description>The UUID of the created dialog transmission. A relative URL to the newly created activity is set in the \"Location\" header.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to create child entity for the given dialog (dialog not owned by authenticated organization or has additional scope requirements defined in service identifiers policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain", "Content-Type: application/json")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/transmissions")]
        Task<IApiResponse<string>> CreateDialogTransmission(System.Guid dialogId, [Body, AliasAs("CreateTransmissionRequest")] CreateTransmissionRequest createTransmissionRequest, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Gets all seen log records for a dialog</summary>
        /// <remarks>Gets all seen log records for a dialog.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog seen log records.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/seenlog")]
        Task<IApiResponse<ICollection<DialogSeenLogSearchItem>>> SearchDialogSeenLogs(System.Guid dialogId, CancellationToken cancellationToken = default);

        /// <summary>Gets end user context system labels for dialogs</summary>
        /// <remarks>
        /// Performs a search for dialog end user context labels, returning a paginated list of dialog ids and end user context revisions.
        /// 
        /// * Party is required.
        /// * System labels are matched with OR semantics.
        /// * See \"continuationToken\" in the response for how to get the next page of results.
        /// * hasNextPage will be set to true if there are more items to get.
        /// </remarks>
        /// <param name="queryParams">The dynamic querystring parameter wrapping all others.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog list.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider.search\".</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/endusercontext")]
        Task<IApiResponse<PaginatedListOfDialogEndUserContextItem>> SearchDialogEndUserContexts([Query] SearchDialogEndUserContextsQueryParams queryParams, CancellationToken cancellationToken = default);

        /// <summary>Gets a list of dialog activities</summary>
        /// <remarks>Gets the list of activities belonging to a dialog</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog activity list.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to get the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/activities")]
        Task<IApiResponse<ICollection<DialogActivitySearchItem>>> SearchDialogActivities(System.Guid dialogId, CancellationToken cancellationToken = default);

        /// <summary>Adds an activity to a dialog's activity history</summary>
        /// <remarks>
        /// The activity is created with the given configuration.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="createActivityRequest">createActivityRequest parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>201</term>
        /// <description>The UUID of the created dialog activity. A relative URL to the newly created activity is set in the \"Location\" header.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to create child entity for the given dialog (dialog not owned by authenticated organization or has additional scope requirements defined in service identifiers policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain", "Content-Type: application/json")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/activities")]
        Task<IApiResponse<string>> CreateDialogActivity(System.Guid dialogId, [Body, AliasAs("CreateActivityRequest")] CreateDialogActivityRequest createActivityRequest, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Gets a list of dialogs</summary>
        /// <remarks>
        /// Performs a search for dialogs, returning a paginated list of dialogs.
        /// 
        /// * All date parameters must contain explicit time zone. Example: 2023-10-27T10:00:00Z or 2023-10-27T10:00:00+01:00
        /// * See "continuationToken" in the response for how to get the next page of results.
        /// * hasNextPage will be set to true if there are more items to get.
        /// </remarks>
        /// <param name="queryParams">The dynamic querystring parameter wrapping all others.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog list.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider.search\".</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs")]
        Task<IApiResponse<PaginatedListOfDialogListItem>> SearchDialogs([Query] SearchDialogsQueryParams? queryParams = default, CancellationToken cancellationToken = default);

        /// <summary>Creates a new dialog</summary>
        /// <remarks>
        /// The dialog is created with the given configuration.
        /// 
        /// For detailed information on validation rules, see [the source for create dialog validators](https://github.com/Altinn/dialogporten/tree/main/src/Digdir.Domain.Dialogporten.Application/Features/V1/ServiceOwner/Dialogs/Commands/Create/Validators)
        /// </remarks>
        /// <param name="dto">dto parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>201</term>
        /// <description>The UUID of the created dialog aggregate. A relative URL to the newly created activity is set in the \"Location\" header.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to create a dialog for the given serviceResource (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Dialog with IdempotentKey 01941821-ffca-73a1-9335-435a882be014 has already been created.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain", "Content-Type: application/json")]
        [Post("/api/v1/serviceowner/dialogs")]
        Task<IApiResponse<string>> CreateDialog([Body] CreateDialog dto, CancellationToken cancellationToken = default);

        /// <summary>Returns a boolean value based on conditions used to determine if a notification is to be sent</summary>
        /// <remarks>Used by Altinn Notification only. Takes a dialogId and returns a boolean value based on conditions used to determine if a notification is to be sent.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="queryParams">The dynamic querystring parameter wrapping all others.</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the notification determination.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"altinn:system/notifications.condition.check\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/actions/should-send-notification")]
        Task<IApiResponse<NotificationCondition>> CheckNotificationCondition(System.Guid dialogId, [Query] CheckNotificationConditionQueryParams queryParams, CancellationToken cancellationToken = default);

        /// <summary>Gets a single dialog transmission</summary>
        /// <remarks>Gets a single transmission belonging to a dialog.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="transmissionId">transmissionId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog transmission.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to get child entity for the given dialog (dialog not owned by authenticated organization or has additional scope requirements defined in service identifiers policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The specified dialog ID or transmission ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/transmissions/{transmissionId}")]
        Task<IApiResponse<DialogTransmissionDetails>> GetDialogTransmission(System.Guid dialogId, System.Guid transmissionId, CancellationToken cancellationToken = default);

        /// <summary>Replaces a transmission</summary>
        /// <remarks>
        /// Replaces a given transmission with the supplied model.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="transmissionId">transmissionId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="updateTransmissionRequest">updateTransmissionRequest parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog transmission was updated successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider.changetransmissions\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to update child entity for the given dialog (dialog not owned by authenticated organization or has additional scope requirements defined in service identifiers policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The specified dialog ID or transmission ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain", "Content-Type: application/json")]
        [Put("/api/v1/serviceowner/dialogs/{dialogId}/transmissions/{transmissionId}")]
        Task<IApiResponse> UpdateDialogTransmission(System.Guid dialogId, System.Guid transmissionId, [Body, AliasAs("UpdateTransmissionRequest")] UpdateTransmissionRequest updateTransmissionRequest, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Gets a single dialog seen log record</summary>
        /// <remarks>Gets a single dialog seen log record.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="seenLogId">seenLogId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog seen log record.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/seenlog/{seenLogId}")]
        Task<IApiResponse<DialogSeenLogDetails>> GetDialogSeenLog(System.Guid dialogId, System.Guid seenLogId, CancellationToken cancellationToken = default);

        /// <summary>Gets a single dialog activity</summary>
        /// <remarks>Gets a single activity belonging to a dialog.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="activityId">activityId parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog activity.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to get child entity for the given dialog (dialog not owned by authenticated organization or has additional scope requirements defined in service identifiers policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The specified dialog ID or activity ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}/activities/{activityId}")]
        Task<IApiResponse<DialogActivityDetails>> GetDialogActivity(System.Guid dialogId, System.Guid activityId, CancellationToken cancellationToken = default);

        /// <summary>Gets a single dialog</summary>
        /// <remarks>
        /// Gets a single dialog aggregate.
        /// 
        /// Note that this operation may return deleted dialogs (see the field `DeletedAt`).
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="endUserId">Filter by end user id</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully returned the dialog aggregate.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to get the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialogs/{dialogId}")]
        Task<IApiResponse<Dialog>> GetDialog(System.Guid dialogId, [Query] string? endUserId = default, CancellationToken cancellationToken = default);

        /// <summary>Replaces a dialog</summary>
        /// <remarks>
        /// Replaces a given dialog with the supplied model.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="dto">dto parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog aggregate was updated successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to update the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain", "Content-Type: application/json")]
        [Put("/api/v1/serviceowner/dialogs/{dialogId}")]
        Task<IApiResponse> UpdateDialog(System.Guid dialogId, [Body] UpdateDialog dto, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Deletes a dialog</summary>
        /// <remarks>
        /// Deletes a given dialog (soft delete).
        /// 
        /// Note that the dialog will still be available on the single details endpoint, but will have a deleted status. It will not appear on the list endpoint for either service owners nor end users.
        /// If end users attempt to access the dialog via the details endpoint, they will get a 410 Gone response.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog aggregate was deleted successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to delete the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain")]
        [Delete("/api/v1/serviceowner/dialogs/{dialogId}")]
        Task<IApiResponse> DeleteDialog(System.Guid dialogId, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Patch a single dialog</summary>
        /// <remarks>
        /// Patches a dialog aggregate with a RFC6902 JSON Patch document. The patch document must be a JSON array of RFC6902 operations.
        /// See [https://tools.ietf.org/html/rfc6902](https://tools.ietf.org/html/rfc6902) for more information.
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not modified/deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="etag">etag parameter</param>
        /// <param name="patchDocument">patchDocument parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>Patch was successfully applied.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \\\"digdir:dialogporten.serviceprovider\\\"</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to update a dialog for the given serviceResource (not owned by authenticated organization or has additional scope requirements defined in policy)</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found or is deleted</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>A server side error occurred.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>The dialog with the given key is removed</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied Revision does not match the current Revision of the dialog</description>
        /// </item>
        /// <item>
        /// <term>422</term>
        /// <description>Domain error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain", "Content-Type: application/json")]
        [Patch("/api/v1/serviceowner/dialogs/{dialogId}")]
        Task<IApiResponse> PatchDialog(System.Guid dialogId, [Body] IEnumerable<JsonPatchOperation> patchDocument, [Header("If-Match")] System.Guid? etag = default, CancellationToken cancellationToken = default);

        /// <summary>Restore a dialog</summary>
        /// <remarks>Restore a dialog.</remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog aggregate was restored successfully.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Forbidden</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/actions/restore")]
        Task<IApiResponse> RestoreDialog(System.Guid dialogId, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Permanently deletes a dialog</summary>
        /// <remarks>
        /// Deletes a given dialog (hard delete).
        /// 
        /// Optimistic concurrency control is implemented using the If-Match header. Supply the Revision value from the GetDialog endpoint to ensure that the dialog is not deleted by another request in the meantime.
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog aggregate was deleted successfully.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to delete the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/actions/purge")]
        Task<IApiResponse> PurgeDialog(System.Guid dialogId, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Freezes a dialog</summary>
        /// <remarks>
        /// Freezes a given dialog.
        /// The dialog cannot be updated/deleted by the service owner (but can still be altered via admin-scope) when frozen
        /// </remarks>
        /// <param name="dialogId">dialogId parameter</param>
        /// <param name="if_Match">if_Match parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>204</term>
        /// <description>The dialog aggregate was frozen successfully.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Unauthorized to freeze the supplied dialog (not owned by authenticated organization or has additional scope requirements defined in policy).</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>The given dialog ID was not found.</description>
        /// </item>
        /// <item>
        /// <term>409</term>
        /// <description>Conflict occurred while processing the request.</description>
        /// </item>
        /// <item>
        /// <term>410</term>
        /// <description>Entity with the given key(s) is removed.</description>
        /// </item>
        /// <item>
        /// <term>412</term>
        /// <description>The supplied If-Match header did not match the current Revision value for the dialog. The request was not applied.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/problem+json, text/plain")]
        [Post("/api/v1/serviceowner/dialogs/{dialogId}/actions/freeze")]
        Task<IApiResponse> FreezeDialog(System.Guid dialogId, [Header("if-Match")] System.Guid? if_Match = default, CancellationToken cancellationToken = default);

        /// <summary>Looks up a dialog by instance reference</summary>
        /// <remarks>Resolves dialog metadata for a supported instance reference in service owner context.</remarks>
        /// <param name="instanceRef">instanceRef parameter</param>
        /// <param name="accept_Language">accept_Language parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Successfully resolved instance reference lookup metadata.</description>
        /// </item>
        /// <item>
        /// <term>400</term>
        /// <description>Validation error occurred. See problem details for a list of errors.</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Missing or invalid authentication token. Requires a Maskinporten-token with the scope \"digdir:dialogporten.serviceprovider\".</description>
        /// </item>
        /// <item>
        /// <term>403</term>
        /// <description>Authenticated service owner does not own the resolved dialog.</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>No dialog match was found for the supplied instance reference.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, application/problem+json, text/plain")]
        [Get("/api/v1/serviceowner/dialoglookup")]
        Task<IApiResponse<ServiceOwnerIdentifierLookup>> GetDialogLookup([Query] string instanceRef, [Header("accept-Language")] AcceptedLanguages? accept_Language = default, CancellationToken cancellationToken = default);
    }

    /// <summary>Gets service resources currently in use in Dialogporten.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "1.7.3.0")]
    public partial interface IMetadataApi
    {
        /// <summary>Gets service resources currently in use in Dialogporten.</summary>
        /// <remarks>Returns public service resource metadata with related service owner, role, and access package metadata.</remarks>
        /// <param name="accept_Language">accept_Language parameter</param>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>Service resource metadata.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain")]
        [Get("/api/v1/metadata/serviceresources")]
        Task<IApiResponse<ServiceResourceMetadataList>> GetServiceResourceMetadata([Header("accept-Language")] AcceptedLanguages? accept_Language = default, CancellationToken cancellationToken = default);

        /// <summary>Gets currently enforced application-level query limits</summary>
        /// <remarks>Returns the active limits for EndUser and ServiceOwner search filters.</remarks>
        /// <param name="cancellationToken">The cancellation token to cancel the request.</param>
        /// <returns>
        /// A <see cref="Task"/> representing the <see cref="IApiResponse"/> instance containing the result:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>200</term>
        /// <description>The currently enforced application-level query limits.</description>
        /// </item>
        /// <item>
        /// <term>503</term>
        /// <description>Service Unavailable, used when Dialogporten is in maintenance mode</description>
        /// </item>
        /// </list>
        /// </returns>
        [Headers("Accept: application/json, text/plain")]
        [Get("/api/v1/metadata/limits")]
        Task<IApiResponse<Limits>> GetLimits(CancellationToken cancellationToken = default);
    }

}
