name: 'Azure Login'
description: 'Login to Azure'

inputs:
  client-id:
    description: 'Azure Client ID'
    required: true
  tenant-id:
    description: 'Azure Tenant ID'
    required: true
  subscription-id:
    description: 'Azure Subscription ID'
    required: false
  allow-no-subscriptions:
    description: 'Allow login without subscription ID'
    required: false
    default: 'false'

env:
  AZ_CLI_VERSION: 2.89.0

runs:
  using: "composite"
  steps:
    - name: OIDC Login to Azure Public Cloud
      uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        subscription-id: ${{ inputs.allow-no-subscriptions == 'true' && '' || inputs.subscription-id }}
        allow-no-subscriptions: ${{ inputs.allow-no-subscriptions }}
