export enum SettingsType {
  contact = `contact`,
  alerts = 'alerts',
  mobileAlerts = 'mobileAlerts',
  emailAlerts = 'emailAlerts',
  emailProfiles = 'emailProfiles',
  mobileProfile = 'mobileProfile',
  companies = 'companies',
  persons = 'persons',
  primary = 'primary',
  profile = 'profile',
  contactAddresses = 'contactAddresses',
  favorites = 'favorites',
  partySettings = 'partySettings',
  partyOverview = 'partyOverview',
  inboxShortcuts = 'inboxShortcuts',
  other = 'other',
}
