@HostAddress = http://localhost:5007
@dialogId = DIALOG_ID_HERE
@dialogToken = "DIALOG_TOKEN_HERE"

### Verify DialogToken

POST {{HostAddress}}/dialogTokenVerify/
Content-Type: application/json

{{dialogToken}}

### Get dialog by id
GET {{HostAddress}}/dialog/{{dialogId}}
Accept: application/json
